name: Build Package

on:
  workflow_dispatch:
  push:
    branches:
      - release

env:
  VERSION: '1.0'
  FINALPACKAGE: 1
  HOMEBREW_NO_AUTO_UPDATE: 1
  HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK: 1

jobs:
  build:
    runs-on: macos-14

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.4'

      # 1. 安装标准 Theos
      - name: Setup Standard Theos
        run: |
          echo "THEOS_IGNORE_PARALLEL_BUILDING_NOTICE=yes" >> $HOME/.theosrc
          bash -c "$(curl -fsSL https://raw.githubusercontent.com/OwnGoalStudio/theos/refs/heads/master/bin/install-theos)"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 2. 安装 RootHide Theos 到 $HOME/theos-roothide
      - name: Setup RootHide Theos
        run: |
          bash -c "$(curl -fsSL https://raw.githubusercontent.com/OwnGoalStudio/theos-roothide/refs/heads/master/bin/install-theos)"
        env:
          THEOS: /Users/runner/theos-roothide
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 3. 编译 arm
      - name: Build (arm)
        run: |
          export THEOS=$HOME/theos
          source devkit/env.sh
          make clean package

      # 4. 编译 arm64 (Rootless)
      - name: Build (arm64)
        run: |
          export THEOS=$HOME/theos
          source devkit/rootless.sh
          make clean package

      # 5. 编译 arm64e (RootHide)
      - name: Build (arm64e)
        run: |
          export THEOS=$HOME/theos-roothide
          source devkit/roothide.sh
          # 关键修改：在这里添加了 ADDITIONAL_CFLAGS 宏定义，在编译时全局禁用警告
          make clean package ADDITIONAL_CFLAGS="-DNO_LIBROOT_WARNING=1"

      - name: Collect dSYMs & Parse Version
        run: |
          mkdir -p ./packages
          find .theos/obj -name "*.dSYM" -exec cp -r {} ./packages/ \; || true
          
          if [ -f .theos/_/DEBIAN/control ]; then
            EXTRACTED_VER=$(grep '^Version:' .theos/_/DEBIAN/control | awk '{print $2}')
            echo "VERSION=$EXTRACTED_VER" >> $GITHUB_ENV
          fi

      - name: Upload dSYMs
        uses: actions/upload-artifact@v4
        with:
          name: symbols-${{ env.VERSION }}
          path: ./packages/*.dSYM

      - name: Upload Packages
        uses: actions/upload-artifact@v4
        with:
          name: packages-${{ env.VERSION }}
          path: ./packages/*.deb

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.VERSION }}
          draft: true
          prerelease: false
          files: ./packages/*.deb
